
[development]
address = "localhost"
port = 8082
workers = 1
log = "normal"

[staging]
address = "0.0.0.0"
port = 8081
log = "normal"
workers = 2

[production]
address = "0.0.0.0"
port = 8080
workers = 2
log = "critical"


